from flask import Flask, jsonify, request, render_template
import os
import sys

# Ensure project modules are importable when running from this subfolder
sys.path.append(os.path.dirname(os.path.dirname(__file__)))
from database import DatabaseManager

app = Flask(__name__)

db = DatabaseManager()

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/api/card')
def get_card():
    card = db.get_card_to_review()
    if not card:
        return jsonify({'available': False})
    return jsonify({'available': True, 'card': {
        'id': card.id,
        'hanzi': card.hanzi,
        'pinyin': card.pinyin,
        'english': card.english,
    }})

@app.route('/api/card/<int:card_id>', methods=['POST'])
def mark_card(card_id):
    data = request.get_json(force=True)
    correct = data.get('correct', False)
    db.update_card_progress(card_id, bool(correct))
    return jsonify({'status': 'ok'})

@app.route('/api/grammar')
def grammar_list():
    points = db.get_all_grammar_points()
    return jsonify([{
        'id': p.id,
        'structure': p.structure,
        'pattern': p.pattern,
        'explanation': p.explanation,
        'status': p.status,
    } for p in points])

@app.route('/api/grammar/<int:grammar_id>', methods=['POST'])
def update_grammar(grammar_id):
    data = request.get_json(force=True)
    status = data.get('status')
    if status:
        db.update_grammar_status(grammar_id, status)
    return jsonify({'status': 'ok'})

@app.route('/api/dashboard')
def dashboard():
    return jsonify(db.get_dashboard_stats())

@app.route('/api/export')
def export_progress():
    # Return raw JSON string generated by the database layer
    json_data = db.export_progress_to_json()
    return app.response_class(json_data, mimetype='application/json')

@app.route('/api/import', methods=['POST'])
def import_progress():
    json_data = request.data.decode('utf-8')
    db.import_progress_from_json(json_data)
    return jsonify({'status': 'ok'})

if __name__ == '__main__':
    app.run(debug=True)
